### ISSUE TITLE
[Feature-Request] Toogle Buttons Display/Hide

### ISSUE THREAD

**Issue by heubergen** [xternal7/ultrawidify#1]
Hi @xternal7 

Great extensions, thanks for that :)
For me, I don't need the many buttons I can remember some keyboard shorcuts like 'w'.

Would love to see a option to disable them.

**Comment by xternal7** [comment]
So I've just added an option that toggles the UI. I've also completely rewrote the code for generating the UI for this and in preparation of some future features. 

I haven't had time to thoroughly test if everything works properly (but so far it doesn't on youtube. Netflix is completely untested at this point), so it could take a while for this feature to see the light of day.

**Comment by heubergen** [comment]
Thank you for the effort, I'm looking forward to test this feature soon :)
