### ISSUE TITLE
[Feature Request] 2.00:1 Ratio

### ISSUE THREAD

**Issue by LexPrima** [xternal7/ultrawidify#10]
Netflix seems to rely on the 2.00:1 aspect ratio. Noticed on Stranger Things and Star Trek: Discovery. Basically speaking black bars on all four sides on wider-than-16:9 screens. While you are at fixing Netflix you could add a button or keyboard shortcut to zoom it fitting.

**Comment by xternal7** [comment]
2:1 (18:9) is supported now (on Firefox version, at least). Do tell me if it's not working properly.

Use extension button in the titlebar or key `x` (default, replaced 16:10 option).
