### ISSUE TITLE
Settings page broken

### ISSUE THREAD

**Issue by xternal7** [xternal7/ultrawidify#16]
Tab switching got broken, presumably while trying to make code more Chrome-friendly? 

Don't know. Saving keyboard shortcuts also doesn't work.

**Comment by Mariusmssj** [comment]
Same issue here, the settings can't be saved as buttons don't work and shortcut text can't even be seen unless you highlight it. Previous versions worked far better

**Comment by xternal7** [comment]
Note to self for later when doing blacklist/whitelist editing: don't use SitesConf.js for storing blacklist/whitelist data. These options should be retrieved from Settings.js. 

Blacklists & whitelists should be text boxes on 'general extension settings' and 'auto-detection settings' pages, not a site-specific setting.

SitesConf should only store site-specific css hacks and other things.

**Comment by System-Glitch** [comment]
Also clicking the autodetection settings does nothing for me on firefox. (I wanted to disable it but I couldn't)

**Comment by xternal7** [comment]
@System-Glitch Well that's a _very_ recent problem (worked a week ago). The fix already up. If auto-update doesn't grab it right away, you can manually download the new version from Mozilla store)

**Comment by System-Glitch** [comment]
Firefox tells me I'm using 3.0.0 which is as far as I know the latest version.

**Comment by xternal7** [comment]
Nope, the most recent version on AMO is 3.0.1 as of two-three hours ago.

**Comment by System-Glitch** [comment]
I can confirm this is fixed with 3.0.1
