### ISSUE TITLE
Shifted Screen

### ISSUE THREAD

**Issue by LexPrima** [xternal7/ultrawidify#17]
#15 this is still happening in chrome

**Comment by xternal7** [comment]
Will push fix when I come home. Thanks for report.

**Comment by xternal7** [comment]
Fix pushed to Chrome store. It should be live in about an hour, if it doesn't update by itself consider reinstalling manually.

If the issue persists feel free to reopen this ticket. (And if you reopen, please include at least the following: browser version and your OS. Knowing other extensions is a nice bonus as well).
