### ISSUE TITLE
BAG

### ISSUE THREAD

**Issue by batyazek** [xternal7/ultrawidify#23]
21:9 doesnt work, AUTO-detect dont work too.when i use hot-key (D) video comes ultra-wide,but а fer seconds after video comes to it first resolution. it s terrible , please fix it

**Comment by xternal7** [comment]
1. Which browser?
2. Which website?
3. Which video (links?)

**Comment by xternal7** [comment]
Assuming this is duplicate of #24, this issue should be fixed.
