### ISSUE TITLE
breaks imgur.com

### ISSUE THREAD

**Issue by Etznab86** [xternal7/ultrawidify#26]
imgur.com gifs stop after 1-2 seconds and go black if ultrawidify is activated. Issue is gone after deactivation.

**Comment by xternal7** [comment]
just adding a test case: https://imgur.com/gallery/AdkGx

In the meantime, do this. This should work. If this option doesn't work, please mention it.

![image](https://user-images.githubusercontent.com/12505802/36622302-c012952a-18fc-11e8-81b7-826626f66b31.png)

**Comment by xternal7** [comment]
Oh yeah, right. Apparently that option doesn't work properly either. I'll try to get a fix out by monday.

**Comment by Etznab86** [comment]
That's great news! I love your app for I own an Ultrawide Screen you help to make as awesome as possible!
Cheers
-------- Ursprüngliche Nachricht --------Von: Tamius Han <notifications@github.com> Datum: 24.02.18  19:25  (GMT+01:00) An: xternal7/ultrawidify <ultrawidify@noreply.github.com> Cc: Etznab86 <etznab@gmx-topmail.de>, Author <author@noreply.github.com> Betreff: Re: [xternal7/ultrawidify] breaks imgur.com (#26) 
Oh yeah, right. Apparently that option doesn't work properly either. I'll try to get a fix out by monday.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xternal7/ultrawidify","title":"xternal7/ultrawidify","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xternal7/ultrawidify"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xternal7 in #26: Oh yeah, right. Apparently that option doesn't work properly either. I'll try to get a fix out by monday."}],"action":{"name":"View Issue","url":"https://github.com/xternal7/ultrawidify/issues/26#issuecomment-368248679"}}}

**Comment by xternal7** [comment]
Okay, imgur is now disabled in Firefox. Something about fix for #24 broke the extension on Chrome, though. Chrome remains at v2.1.2 (with reddit and imgur still not blacklisted). 

I'll close this issue now as it's fixed, even though it'll take a while for changes to land in Chrome (chrome problems will be getting troubleshooted when I manage to write fixes for #25, #27, #28.
