### ISSUE TITLE
Player buttons not showing (or were they removed?)

### ISSUE THREAD

**Issue by System-Glitch** [xternal7/ultrawidify#29]
**Description:** The buttons in the player are now missing for me. Is it intentional?  
**Browser:** Firefox, up to date  
**Frequency:** Always  
**How to reproduce:** I have unfortunately no idea. It happened after an update of the add-on, but I can't tell which one.

**Comment by xternal7** [comment]
They were removed when the extension was rewritten from ground up (this was necessary because the old code was a mess). I don't plan to re-add them at this time. Maybe after I manage to finish all the other, more important features, but with amount of work ahead this doesn't seem too likely.

**Comment by xternal7** [comment]
Thanks for taking time to report the perceived issue, though. Much appreciated.
