### ISSUE TITLE
Zoom in on Netflix using Linux doesn't zoom

### ISSUE THREAD

**Issue by Cybolic** [xternal7/ultrawidify#3]
Pressing zoom in just leaves the video at about half the size of the screen and doesn't change on consecutive presses; pressing zoom out makes the video even smaller.
I should note that pressing zoom in after pressing zoom out, does change the video size back to about half the screen, so it seems it's the maximum zoom size that's wrongly detected.

This is using Firefox 50.1.0 on Ubuntu Gnome 16.10, extension version 1.1.0.

**Comment by xternal7** [comment]
So I've found and fixed the issue. Fix has been pushed, but it's going to take a few days to get the fix to AMO (I've got some other issues to fix as well)

* There seems to be a related issue ('reset' after zooming doesn't work properly, similar to the zooming issue).

**Comment by xternal7** [comment]
Also fixed the 'reset' issue.
