### ISSUE TITLE
Doesn't work at all after the update

### ISSUE THREAD

**Issue by Ridha92** [xternal7/ultrawidify#31]
Before the last update, the extension worked very well, but now nothing works!
It was working perfectly on Youtube videos! Please bring back the old update.

**Comment by xternal7** [comment]
So I'll need, at the very minimum:

* Browser

Would also be nice to know

* what's the "old update" but that's not quite realistic (as I don't think browsers even give out that info)

**Comment by Ridha92** [comment]
Google Chrome
I believe it was working on version 1.x 
my screen show black bars on the side on YouTube videos but this add-on used to fix the issue. Non of the buttons in the settings take effect.

**Comment by xternal7** [comment]
Have you tried uninstalling and reinstalling? There's a possibility that settings got corrupted, and I don't think I pushed the fix for that to Chrome yet. I think that was conclusion to the #21
