### ISSUE TITLE
Breaks GIFs in reddit

### ISSUE THREAD

**Issue by zoulock** [xternal7/ultrawidify#33]
I have to disable the add-on each time I go to reddit because the GIFs are broken (only the corner appears).

**Comment by xternal7** [comment]
Which version of the addon do you have? Do you have the latest version of the extension (depending on the browser, v2.2.2.2/v2.2.1)? 

This issue should be _fixed fixed_ in versions 2.2.2.2 (firefox) and 2.2.1 (Chrome), along with one bigger issue. However, these two versions are fairly new (we're talking about this-wednesday/thursday-new) so Firefox/Chrome may have not updated the extension for you yet.

**Comment by zoulock** [comment]
Oh, my bad, you were right, I was using the old version. Seems fixed with the new one.
