### ISSUE TITLE
Video zooms in black frames

### ISSUE THREAD

**Issue by zoulock** [xternal7/ultrawidify#36]
When I'm watching a 16:9 video and black frames appear with nothing or something in the center of them (such as movie credits), the video scales even though it may scale just a black frame.
Could it be possible to change sensitivity or change the algorithm to check if there is something else than a (mostly) black frame to be scaled?

**Comment by xternal7** [comment]
Yes, that would be possible. Maybe I'll manage to hack something together this or next weekend but I'm making no committments.

**Comment by xternal7** [comment]
As of 4.0, video sensitivities can be adjusted + there were additional improvements to aspect ratio detection that try to not trigger autodetection on black screens with text (though this mostly appears to small title credits and wasn't tested with end-movie credits). Text must be of single color.
