### ISSUE TITLE
Fullscreen broken for 4:3 videos

### ISSUE THREAD

**Issue by XtremAlRaven** [xternal7/ultrawidify#38]
For example, this video: https://www.youtube.com/watch?v=JXbLyi5wgeg
It's 4:3, so there's nothing really for the plugin to do. But in fullscreen it doesn't get stretched properly to fit height - it just stays as 4:3 in the upper part of the screen. And there's no setting in the plugin to let this video be.
So to watch it in fullscreen it is needed to switch the extension off, restart the page and watch it. (And after that, if I want to continue using this extension, switch it back on.) At least, that's the only way I could find to make it work.

**Comment by xternal7** [comment]
Chrome or Firefox, and which version?

Because I can't reproduce that in Firefox.

>But in fullscreen it doesn't get stretched properly to fit height - it just stays as 4:3 in the upper part of the screen.

1. Are you using theater mode?
2. Does this happen with 16:9 videos as well?
