### ISSUE TITLE
Version 3.1.0 is buggy!

### ISSUE THREAD

**Issue by Shadoware** [xternal7/ultrawidify#47]
Latest version(3.1.0) is causing problems in youtube and Netflix. Its making the video controls unresponsive, not showing subtitles correctly randomly and others. The former version worked with no meaningful problems!
 
I tried to configure it to not be activated on certain websites like Netflix but this config dont work correctly.

I use Windows 10 64-bit and Firefox 62.0 64-bit

**Comment by xternal7** [comment]
Firefox: it appears randomly (not all installs I have suffer from that). Somehow _NOT_ present in Chrome version.

**Comment by xternal7** [comment]
>I tried to configure it to not be activated on certain websites like Netflix but this config dont work correctly.

Okay try this for shits and giggles: 

1. open the popup and note what the default options are
2. try changing settings via the popup
3. close the popup
4. open the popup again

If popup looks the same as it did in step one, open a new tab (or switch to an already opened tab) and then switch back to netflix. Repeat the above procedure. Do the settings save now?

~~I'm just trying to determine if I've found this bug with settings not working correctly~~

**Comment by xternal7** [comment]
The bug with settings not saving/not working properly should be fixed (assuming you've experienced the same bug that I noticed in the code).

Version 3.2.0 is going to be out by the morning.
