### ISSUE TITLE
enable changing or disabling of shortcuts

### ISSUE THREAD

**Issue by seba-eng** [xternal7/ultrawidify#49]
the keyboard shortcuts can be helpful, but can althogh be quite anoying sometimes. When you type a comment on yotube, the aspect ratio of the video changes everytime you hit one of the keys used. It would be great if you were able to change or disable the shortcuts.

**Comment by xternal7** [comment]
Not this shit again.

By the way, extension is supposed to detect when you're typing a comment and ignore keyboard shortcuts while a text box or a search box is focused, and I'm pretty sure I was fixing and fixed this issue some time in the last 3-4 months once already, but it seems to have made a comeback.

Notes for any programmer stumbling over this before I get around to fixing this issue again:

```
    var activeElement = document.activeElement;
    if( (! PlayerData.isFullScreen()) && (
      (this.inputs.indexOf(activeElement.tagName.toLocaleLowerCase()) !== -1) ||
      (activeElement.getAttribute("role") === "textbox") ||
      (activeElement.getAttribute("type") === "text")
    )){
      if(Debug.debug && Debug.keyboard)
        console.log("[Keybinds::_kbd_process] We're writing a comment or something. Doing nothing");
      return;
    }
  ```
PlayerData.isFullScreen(): 
```
 static isFullScreen(){
    return ( window.innerHeight == window.screen.height && window.innerWidth == window.screen.width);
  }
```

How doesn't this _not_ ignore the keypress when in textbox? It's probably some dumb issue but still.
