### ISSUE TITLE
ultrawidify firefox addon won't addon

### ISSUE THREAD

**Issue by enigmos74** [xternal7/ultrawidify#61]
ultrawidify Firefox addon won't addon.
I had it working then it uninstalled by itself including my video downloader addon for fire fox.
I've tried to reinstall but it no longer works.

**Comment by xternal7** [comment]
This is an issue with Firefox: https://www.engadget.com/2019/05/03/firefox-extension-add-on-cert/

[Here's how you fix it](https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/16): 

>We rolled-out a fix for release, beta and nightly users on Desktop. The fix will be automatically applied in the background within the next few hours, you don’t need to take active steps.

>In order to be able to provide this fix on short notice, we are using the Studies system. You can check if you have studies enabled by going to Firefox Preferences -> Privacy & Security -> Allow Firefox to install and run studies.

>You can disable studies again after your add-ons have been re-enabled.
