### ISSUE TITLE
Preview version release issue: Videos not aligning properly/consistantly

### ISSUE THREAD

**Issue by yusareba** [xternal7/ultrawidify#62]
Describe the bug:
This issue has only be observed on YouTube, though it may likely affect other platforms. Although it has also been observed on the latest version of Vivaldi (Chromium). 

Videos are occasionally aligned incorrectly despite extension & site tab being set as center/default. I also noticed that under the video tab, no selections are highlighted, even if user attempts to select. Often times when an alignment is selected on the extension tab, upon refreshing or navigating elsewhere, the alignment setting doesn't visually appear to save. For example, if you set the extension tab to align right, then refresh- Sometimes the video will be aligned right, other times center. 

Normally this wouldn't be an issue, because I personally never align videos anywhere but center, however sometimes it makes the mistake of aligning left even when settings are set to center & default. The problem can be temporarily resolved by selecting 'center' under the extension tab, though as stated before upon refresh or navigation, the video may return to aligning left unless resolved again. Lastly, the issue will resolve (align center/default) on it's own if the extension resizes the video due to black bars as per its' standard function.

To Reproduce:
After uninstalling the latest official version of Ultrawidify (3.2.2) & other possible conflicting extensions, the issue can be reproduced by installing the unreleased version of the extension. 
Alignment issues may happen at random, so it isn't very consistent. You may have to select some alignments under the extension & site settings tabs. Notably center/default under site settings)
You should also notice that settings under the video tab do not show yellow highlights that indicate settings have been selected.

Expected Behavior:
I would expect that the video default to align center as set by default under extension & site settings tabs. 

Screenshots:
N/A

Browser and OS:
- Browser: Version 74.0.3729.131 (Official Build) (64-bit) & Vivaldi (Chromium) 2.5.1525.40 (64-bit)
- Operating System: Windows 10 Pro
- Ultrawidify Version: Unreleased (After 3.2.2)

Additional info:
If I come across additional & unrelated issues, I will create new individual posts as to create distinct points per issue if/as they arise.

**Comment by xternal7** [comment]
Thanks for the report.

I'll need to examine the alignment issue a bit more. So far, I haven't been too successful in figuring it out.

>You should also notice that settings under the video tab do not show yellow highlights that indicate settings have been selected.

This is by design. It's a bit shitty design, that much I'll admit. Mostly because keeping track of what's selected on current video gets a bit annoying, especially once you start switching tabs (or if you watch two embedded yotube videos at the same time).

**Comment by yusareba** [comment]
Is it possible that I can have the previous version (3.2.2) similar to the beta one released? I'm still getting alignment issues.

Also i'll see if I can make a video showing the problem

**Comment by xternal7** [comment]
Hey wait a minute. Whom did I send the second beta, then?

Anyway I can't reproduce. Please do me a favour and go to extension settings page [this link assuming extension ID is the same across all chrome installs](chrome://extensions/?id=dndehlekllfkaijdlokmmicgnlanfjbi). 

Select tab `Super advanced settings`. Select everything, copy, paste in a file, attach the file. (Alternatively, paste into [gist](https://gist.github.com/) and share link).

![pic](https://user-images.githubusercontent.com/12505802/58919955-612c8b80-8730-11e9-8842-b6cda54a86cd.png)

After you've copy&pasted the text, go to 'General Settings' and click 'Reset settings' at the bottom. 

Does the issue still happen?

**Comment by xternal7** [comment]
RE:

> Is it possible that I can have the previous version (3.2.2) similar to the beta one released?

Borderline impossible because my github practices are shitty.

**Comment by xternal7** [comment]
In retrospect, this smells _very_ similar to #67 (except I could reproduce that one because it lay dormant until Iridium made it pop). I'll call it _very_ probably fixed, though without ability to reproduce it when Iridium isn't running/installed makes it hard to say for sure.

I'll be marking this closed. The version that probably fixes this issue is gonna be released some time this weekend if all goes according to plan.
