### ISSUE TITLE
Extensions pauses video on Netflix Interactive Content

### ISSUE THREAD

**Issue by LeonStaufer** [xternal7/ultrawidify#63]
**Describe the bug**
When watching [interactive content](https://help.netflix.com/en/node/62526) on Netflix, the extension "breaks" in several weird ways:
  * randomly pauses the playback,
  * the pause screen persists after resuming playback,
  * controls (especially the character choice actions) are lagging significantly.

**To Reproduce**
Watch interactive content on Netflix.

**Expected behavior**
None of the above ;)

**Screenshots**
[Video depicting the persistent pause screen](https://streamable.com/naama)

**Browser and OS**
 * Browser/browser version: Firefox 63.0b3
 * Operating system: Windows 10 Pro
 * Intel i7 4790k, 16 GB RAM, GTX 970
 * Ultrawidify version: 3.2.2

**Additional info**
Thank you for developing this extension :)

**Comment by LeonStaufer** [comment]
I'm having more bad luck. To add to the issue, using the add on for an extended period of time sometimes causes Netflix to refresh, or the video quality to change. (At this point I have no clue how this is related to the add on, however, removing it, resolves all the issues).

Another problem I just encountered was flickering (probably due to quick changes in the aspect ratio, however, without input on my side)
Here is [a video](https://streamable.com/usvp7) of it.

**Comment by xternal7** [comment]
What happens if you use [this beta version](tamius.net/ultrawidify/versions-git/ultrawidify_git-4.0.0a2-fx.xpi) instead?

**Comment by LeonStaufer** [comment]
Thanks for the quick reply.

All of these are fixed: 
  *  randomly pauses the playback,
  *  the pause screen persists after resuming playback,
  *  controls (especially the character choice actions) are lagging significantly.

and I couldn't reproduce the flickering either, so yay, all seems good :)
