### ISSUE TITLE
[Feature Request] Brave Browser

### ISSUE THREAD

**Issue by TangoFox4** [xternal7/ultrawidify#7]
Please add support for the Brave Browser? It is noice :)

https://brave.com/

**Comment by xternal7** [comment]
I'll try looking at it at some point. In the mean time, I've noticed that brave apparently uses Chrome extensions (?), so:

1. Have you tried installing the [chrome version](https://chrome.google.com/webstore/detail/ultrawidify/dndehlekllfkaijdlokmmicgnlanfjbi)?
2. Does it work?

**Comment by TangoFox4** [comment]
Mmmh, how?

**Comment by xternal7** [comment]
https://www.brave.com/loading-chrome-extensions-in-brave/

This might be your best shot, seeing how the documentation for brave browser is ~~absolutely trash~~ seemingly non-existent.

**Comment by TangoFox4** [comment]
Uff, thats too complicated for me, sry :(

**Comment by xternal7** [comment]
Well, unfortunately there doesn't seem to be any documentation on how to port the extension over to the Brave browser. (Although I could be wrong on this one)

Do you use any other browser extensions with Brave. If yes, which and where did you install them from?

**Comment by TangoFox4** [comment]
I use 1password. It is in Settings > Add-Ons. It is just there, build in.

I also found this about adding chrome-addons: https://github.com/brave/browser-laptop/issues/253
It seems to be on their timeline?

**Comment by xternal7** [comment]
It appears that [Brave now supports chrome extensions off  the shelf](https://www.cnet.com/news/brave-ad-blocking-browser-gets-chrome-extensions-with-major-new-version/) - in the dev version at least.

Haven't really tested anything because at this point any Brave-specific problem is prolly caused by Brave.
