### ISSUE TITLE
Causing video players to jum around

### ISSUE THREAD

**Issue by jaredbm** [xternal7/ultrawidify#71]
Causing unmaximized Facebook videos to jump around. Have also seen it in other places with video players
**Browser and OS**
 * Browser/browser version: Firefox 68.0.2 
 * Operating system:MacOS
 * Ultrawidify version:4.2.3.3

**Additional info**
Any other things you want to say.

**Comment by xternal7** [comment]
You mean "unmaximized" as in home feed:

![image](https://user-images.githubusercontent.com/12505802/64056879-fa840600-cb96-11e9-9ed9-d0f2efdd2fdc.png)

Or do you mean when watching non-fullscreen like this:

![image](https://user-images.githubusercontent.com/12505802/64056940-60708d80-cb97-11e9-9e5d-bcf1ba693ab0.png)

Or is it something else? I'm having issues reproducing this problem now.

**Comment by xternal7** [comment]
Status update: managed to reproduce on Win10 machine.

So this is OS dependant. Okay then.

V V pet., 30. avg. 2019 ob 18:49 je oseba jaredbm <notifications@github.com<mailto:notifications@github.com>> napisala:

Causing unmaximized Facebook videos to jump around. Have also seen it in other places with video players
Browser and OS

  *   Browser/browser version: Firefox 68.0.2
  *   Operating system:MacOS
  *   Ultrawidify version:4.2.3.3

Additional info
Any other things you want to say.

**Comment by xternal7** [comment]
This issue should be fixed. Update is being uploaded to AMO and Chrome Web Store and will be available in a few hours. Browsers should automatically download said update in a day or two.

If the issue _still_ isn't fixed for you, please feel free to reopen this issue.
