### ISSUE TITLE
Video not correctly aligned on youtube!

### ISSUE THREAD

**Issue by Shadoware** [xternal7/ultrawidify#73]
**Describe the bug**
I disabled auto-detection on youtube however sometimes, videos become misaligned.

**To Reproduce**
Watch some youtube videos.

**Expected behavior**
Video aligned.

**Screenshots**
https://ibb.co/vvjfgMr

**Browser and OS**
 * Firefox 68.0.2
 * Windows 10 64-bit
 * Version: 4.2.4.2

**Comment by xternal7** [comment]
1. Does this happen when you go from/to fullscreen?
2. Any _specific_ video where that happens? Ran through a few videos and didn't get that problem.
3. Does refresh (f5) fix the problem? (This is not a fix, but knowing that narrows the options down a bit)
4. Do you have any other, additional extensions for youtube?

I can't reproduce this bug in version 4.2.4.2, but I did encounter (and fix) something similar earlier last week in an unreleased version ...

**Comment by xternal7** [comment]
Oi yey, happens when resizing browser window. Likely related to #72 (& fix exists, but I'll know for sure tomorrow)

**Comment by Shadoware** [comment]
>     1. Does this happen when you go from/to fullscreen?
>     2. Any _specific_ video where that happens? Ran through a few videos and didn't get that problem.
>     3. Does refresh (f5) fix the problem? (This is not a fix, but knowing that narrows the options down a bit)
>     4. Do you have any other, additional extensions for youtube?
> I can't reproduce this bug in version 4.2.4.2, but I did encounter (and fix) something similar earlier last week in an unreleased version ...

1 - Yes, I think it occurs mainly in this situation.
2 - It happened in many videos. I dont remember only one specifically.
3 - Sometimes. If I click any button related to alignment usually the video returns to normal too.
4 - I also use "Enhancer for youtube" and "Hide youtube fullscreen controls".

Ultrawidify is an extremely usefull extension for those using ultrawide displays but I returned to version 3.1.0 because its the one that works more perfectly to me.
This last version also has an strange problem, if I choose something related to whitelist the section where shows site specific options become disabled so whitelist makes no sense in this version.

Version 3.2.2 also seems good but it make the videos slow to pause/play on mouse click. I always find some kind of bug with most versions.

**Comment by Shadoware** [comment]
I didn't mean to close to topic. Sorry.

**Comment by xternal7** [comment]
> This last version also has an strange problem, if I choose something related to whitelist the section where shows site specific options become disabled so whitelist makes no sense in this version.

That's prolly been there for a while, then, but should be an easy one. I'm gonna make a note of that ...

**Comment by xternal7** [comment]
Update that fixes this issue has been released.

Thought I've fixed #75 ('whitelist only' disables site tab) as well but nope, that one remains open.

**Comment by xternal7** [comment]
Okay, the 'whitelist only' issue also seems to be fixed, actually.
