### ISSUE TITLE
Pressing P will make the youtube video move around.

### ISSUE THREAD

**Issue by SimplyJeevS** [xternal7/ultrawidify#78]
When watching a youtube video and pressing p the video will start sliding around, following your mouse. (this also happens when you happen to type the letter p in a comment.) and as far as i see there is no way to turn it off. i would like to request you allow us to turn this feature off.

screenshots: http://prntscr.com/pbup7k http://prntscr.com/pbupgr

browser used is vivaldi
os is windows 10
ultrawidify is latest build

**Comment by xternal7** [comment]
Thanks for the report.

* pressing P again will stop the video from sliding around
* keyboard shortcuts can be disabled on per-site basis (normally, the extension should detect when you're typing a comment. For some reason, though, this doesn't work on youtube. I'm still trying to figure that one out)

> and as far as i see there is no way to turn it off. 

There is, but it appears that the backwoods known as the settings page is broken at the moment so I'm gonna to fix that real quick. If settings pages were functional, that's:

**Settings > Actions > pan > delete** (click the X)

But it's not so I'll get back to you once it is.

**Comment by xternal7** [comment]
So this is ever so slightly changed for 4.3.1

**1. Click pencil.**
![image](https://user-images.githubusercontent.com/12505802/65805397-a5331880-e185-11e9-9b99-f2cfc9b227c1.png)

**2. Click 'clear shortcut', click save** (Note: after clearing the shortcut, shortcut will still remain incorrectly displayed until you click save)
![image](https://user-images.githubusercontent.com/12505802/65805411-b5e38e80-e185-11e9-9c21-9df492634fa1.png)
