### ISSUE TITLE
Youtube videos starts to stuttering

### ISSUE THREAD

**Issue by qantumforce** [xternal7/ultrawidify#83]
Youtube in fullscreen seems to stuttering ( looks like FPS/V-sync problem in games). Without plugin works normally. Also without fullscreen but with plugin works fine. 

 * Browser/browser version: Firefox 71
 * Operating system: Windows 10
 * Ultrawidify version: 4.4.2

**Comment by xternal7** [comment]
I'm gonna need some more info. 

* What's your CPU, GPU, RAM.
* Does the issue only happen on youtube or does it happen on other sites as well?
* Have you cranked autodetection frequency past defaults?

Then, open extension settings and in this order:

* Try lowering the frequency of autodetection
* Try disabling auto-detection altogether

Did that help?

**Comment by qantumforce** [comment]
Ok. I managed to fix this problem.
I had to reinstall driver with DDU and reset plugin and now is fine. 
Probably Nvidia experience damaged my GPU driver. 

Well, I'm sorry I bothered you.
