### ISSUE TITLE
The pop-up is blackedout, ext not working

### ISSUE THREAD

**Issue by Quirinovsky** [xternal7/ultrawidify#86]
Pop-up all black in any site I try (youtube, netflix) and ext doesn't work

**To Reproduce**
Just tried to use it 

**Expected behavior**
The options should appear on the pop-up and t he extension should work

**Screenshots**
![image](https://user-images.githubusercontent.com/59506858/71766645-e2bfe400-2ee0-11ea-9bae-d60b9c405ee3.png)

**Browser and OS**
 * Browser/browser version: firefox, the 71.0
 * Operating system: W10
 * Ultrawidify version: the last one

**Comment by xternal7** [comment]
Thanks for the report. I think I've found the issue. Fix will be up shortly.

In the mean time — as a workaround — keyboard shortcuts still work.
