### ISSUE TITLE
Video shifts to the side when YouTube ambilight is enabled along with Ultrawidify. 

### ISSUE THREAD

**Issue by iGerman00** [xternal7/ultrawidify#88]
**Describe the bug**
I have [YouTube Ambilight](https://github.com/WesselKroos/chrome-youtube-ambilight) installed through the [Opera Web Store](https://addons.opera.com/en/extensions/details/youtube-ambilight/), and Ultrawidify off the Chrome Store. Using both of these plugins at the same time seems to cause the video shifting to the left, rendering some content not visible sometimes even. 

**To Reproduce**
Install YouTube Ambilight
Install Ultrawidify
Turn on both, Ultrawidify set on auto mode.
*note: YT Ambilight turn on hotkey is "A"*

**Expected behavior**
Neither the video nor the ambilight behind it should move, and if possible, the ambilight should also scale and move with the main video itself.

**Screenshots**
This is YouTube Ambilight being enabled and disabled here. Disabling Ultrawidify as an extension also fixes the issue:

[Enabled](https://i.imgur.com/Qo3nz4D.jpg)
[Disabled](https://i.imgur.com/U1sxQ0U.jpg)

**Browser and OS**
 * Browser version: Opera GX version LVL 1 (core: 64.0.3417.150)
 * Operating system: Windows 10 Build 1909
 * Ultrawidify version: Version 4.4.3.1

**Additional info**

Issue is also on YouTube Ambilight's GitHub. Ultrawidify is installed from the Chrome Store on Opera with the Install Chrome Extensions extension.

**Comment by WesselKroos** [comment]
This issue can be closed. I've found a fix that I can apply in the YouTube Ambilight extension.

**Comment by xternal7** [comment]
By the way, if I may ask — what was the fix? 

For future notice.

**Comment by WesselKroos** [comment]
Sure,

In my extension there is an option to add a box-shadow around the video. To do that I resize the parent div of the video tag from a full window width to the width of the video tag. But your extension is using the width of the parent to calculate and set the position of the video tag. So the video tag was moved to much to the left and the video was cropped to much.

My extension creates a separate container div in the body element for all kind of visuals. So I was able to move the video shadow to a new div within that container. I'm now moving that div behind the position of the video tag to create the same effect.

I hope separating that from the video tag itself fixes any conflicts between our extensions and also some currently unknown conflicts between other extensions as well.

**Comment by tamius-han** [comment]
> To do that I resize the parent div of the video tag from a full window width to the width of the video tag. But your extension is using the width of the parent to calculate and set the position of the video tag.

Yeah, that's correct-ish (I'm looking the player element by id on youtube). It's necessary in order to work with videos and video players of arbitrary aspect ratios. 

Another thing that I sometimes do (but only rarely) is that I force width of the player element (e.g. necessity on vimeo), but that's not going to be a problem for you.

>I hope separating that from the video tag itself fixes any conflicts between our extensions and also some currently unknown conflicts between other extensions as well.

Yeah, that should fix the problems in theory.
